version: '1'
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  act4:
    image: guillepena94/eoi-fastapi-act4:latest
    container_name: act4
    ports:
      - "4242:4242"
    environment:
      - API_KEY=14519740638093073631004983047404764
      - SECRET_KEY=025atj2lCv9bvk5Q5d3Ocxz04gBdXwlx
      - ALGORITHM=HS512
    depends_on:
      - redis
      
